# Site settings
title: pororysue Blog
email: pororysue@gmail.com
baseurl: ""
permalink: /:categories/:year/:month/:day/:title
url: "http://pororysue.github.io"
name: "Suemiere.B"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Build settings
markdown: kramdown
timezone: +3733+12658
encoding: utf-8
